export { default as client } from './config'
export { account, databases, storage, ID, Query } from './config'
export { authService } from './auth'
export type { User } from './auth'
export { databaseService } from './database'
export type { Document } from './database'
export { storageService } from './storage'
export type { File } from './storage'
